export const HandleClickDisable = 'handleClickDisable'
export const HandleClickSize = 'handleClickSize'
export const HandleClickUninstall = 'handleClickUninstall'
export const HandleFeaturesClick = 'handleFeaturesClick'
export const HandleReadmeContextMenu = 'handleReadmeContextMenu'
export const HandleTabsClick = 'handleTabsClick'
